name: Foo CI

on: [pull_request, push]

jobs:
    tests:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x, 20.x]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}
            - name: npm install
              run: npm ci
            - name: tests
              run: npm test
